In [1]:
import export_food_data
import pandas as pd

In [2]:
food_nutrients = export_food_data.get_nutri_data_table()

In [5]:
food_nutrients

,id,fdc_id,nutrient_id,amount,data_points,derivation_id,min,max,median,footnote,min_year_acquired
0,1283684,167512,1005,41.18,0.0,49.0,NaN,NaN,NaN,NaN,NaN
1,1283687,167512,2000,5.88,1.0,46.0,NaN,NaN,NaN,NaN,NaN
2,1283686,167512,1051,35.50,1.0,46.0,NaN,NaN,NaN,NaN,NaN
3,1283685,167512,1008,307.00,0.0,49.0,NaN,NaN,NaN,NaN,NaN
4,1283683,167512,1004,13.24,1.0,46.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
6173455,9923472,810276,1005,10.00,NaN,71.0,NaN,NaN,NaN,NaN,NaN
6173456,9923470,810276,1004,1.25,NaN,71.0,NaN,NaN,NaN,NaN,NaN
6173457,9923468,810276,1003,1.67,NaN,71.0,NaN,NaN,NaN,NaN,NaN
6173458,9923482,810276,1089,0.67,NaN,71.0,NaN,NaN,NaN,NaN,NaN
6173459,9923480,810276,1087,25.00,NaN,71.0,NaN,NaN,NaN,NaN,NaN

In [4]:
food_nutrients.sort_values("fdc_id", 
                           inplace=True,ignore_index=True)

In [6]:
df = food_nutrients.pivot(index="fdc_id",columns="nutrient_id",values="amount")

In [7]:
df

nutrient_id,1002,1003,1004,1005,1007,1008,1009,1010,1011,1012,...,2021,2022,2023,2024,2025,2026,2028,2029,2032,2033
fdc_id,,,,,,,,,,,,,,,,,,,,,
167512,NaN,5.88,13.24,41.18,3.50,307.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
167513,NaN,4.34,11.27,53.42,3.08,330.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
167514,NaN,6.10,3.70,79.80,7.20,377.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
167515,NaN,8.00,1.80,46.00,1.60,232.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
167516,NaN,6.58,9.22,41.05,2.81,273.0,35.51,2.67,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
810268,NaN,0.83,0.00,2.50,NaN,12.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
810270,NaN,0.83,0.00,2.50,NaN,12.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
810272,NaN,2.08,0.42,5.42,NaN,33.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
810274,NaN,2.40,0.00,8.80,NaN,48.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
810276,NaN,1.67,1.25,10.00,NaN,58.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
foods = export_food_data.get_food_table(usecols=["description", "data_type"])

In [9]:
foods

              data_type                                        description
fdc_id
344604     branded_food  Tutturosso Green 14.5oz. NSA Italian Diced Tom...
344605     branded_food    Tutturosso Green 14.5oz. Italian Diced Tomatoes
344606     branded_food    Honeysuckle White Fresh 97% Ground White Turkey
344607     branded_food          Honeysuckle White 97% Ground White Turkey
344608     branded_food                Honeysuckle Whtie 85% Ground Turkey
...                 ...                                                ...
334717  sub_sample_food  Sugars, Pupusas, Bean, flat stuffed corn biscu...
334718  sub_sample_food  Thiamin, Pupusas, Bean, flat stuffed corn bisc...
334719  sub_sample_food  Vitamin K, Pupusas, Bean, flat stuffed corn bi...
334720  foundation_food  Restaurant, Latino, pupusas con frijoles (pupu...
746774  foundation_food           Restaurant, Chinese, sweet and sour pork

[390292 rows x 2 columns]

In [10]:
final = pd.concat([df, foods], axis=1, join='inner')

In [11]:
final

,1002,1003,1004,1005,1007,1008,1009,1010,1011,1012,...,2023,2024,2025,2026,2028,2029,2032,2033,data_type,description
fdc_id,,,,,,,,,,,,,,,,,,,,,
167512,NaN,5.88,13.24,41.18,3.50,307.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,sr_legacy_food,"Pillsbury Golden Layer Buttermilk Biscuits, Ar..."
167513,NaN,4.34,11.27,53.42,3.08,330.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,sr_legacy_food,"Pillsbury, Cinnamon Rolls with Icing, refriger..."
167514,NaN,6.10,3.70,79.80,7.20,377.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,sr_legacy_food,"Kraft Foods, Shake N Bake Original Recipe, Coa..."
167515,NaN,8.00,1.80,46.00,1.60,232.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,sr_legacy_food,"George Weston Bakeries, Thomas English Muffins"
167516,NaN,6.58,9.22,41.05,2.81,273.0,35.51,2.67,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,sr_legacy_food,"Waffles, buttermilk, frozen, ready-to-heat"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
810268,NaN,0.83,0.00,2.50,NaN,12.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,branded_food,Santiam French Style Green Beans 14.5oz
810270,NaN,0.83,0.00,2.50,NaN,12.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,branded_food,Santiam Cut Wax Beans 14.5oz
810272,NaN,2.08,0.42,5.42,NaN,33.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,branded_food,CAMPBELL'S CHUNKY SOUP CHICKEN & VEGETABLE
810274,NaN,2.40,0.00,8.80,NaN,48.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,branded_food,Santiam Sweet Peas 15oz
810276,NaN,1.67,1.25,10.00,NaN,58.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,branded_food,PREGO SAUCES TOMATO & MUSHROOM

In [12]:
nutri_dict= export_food_data.get_nutrient_dict()

In [13]:
nutri_dict

{1002: {'name': 'Nitrogen', 'unit_name': 'G'},
 1003: {'name': 'Protein', 'unit_name': 'G'},
 1004: {'name': 'Total lipid (fat)', 'unit_name': 'G'},
 1005: {'name': 'Carbohydrate, by difference', 'unit_name': 'G'},
 1007: {'name': 'Ash', 'unit_name': 'G'},
 1008: {'name': 'Energy', 'unit_name': 'KCAL'},
 1009: {'name': 'Starch', 'unit_name': 'G'},
 1010: {'name': 'Sucrose', 'unit_name': 'G'},
 1011: {'name': 'Glucose (dextrose)', 'unit_name': 'G'},
 1012: {'name': 'Fructose', 'unit_name': 'G'},
 1013: {'name': 'Lactose', 'unit_name': 'G'},
 1014: {'name': 'Maltose', 'unit_name': 'G'},
 1018: {'name': 'Alcohol, ethyl', 'unit_name': 'G'},
 1024: {'name': 'Specific Gravity', 'unit_name': 'SP_GR'},
 1026: {'name': 'Acetic acid', 'unit_name': 'MG'},
 1032: {'name': 'Citric acid', 'unit_name': 'MG'},
 1038: {'name': 'Lactic acid', 'unit_name': 'MG'},
 1039: {'name': 'Malic acid', 'unit_name': 'MG'},
 1050: {'name': 'Carbohydrate, by summation', 'unit_name': 'G'},
 1051: {'name': 'Water', 'unit_name': 'G'},
 1056: {'name': 'Sorbitol', 'unit_name': 'G'},
 1057: {'name': 'Caffeine', 'unit_name': 'MG'},
 1058: {'name': 'Theobromine', 'unit_name': 'MG'},
 1062: {'name': 'Energy', 'unit_name': 'kJ'},
 1063: {'name': 'Sugars, Total NLEA', 'unit_name': 'G'},
 1072: {'name': 'Carbohydrate, other', 'unit_name': 'G'},
 1075: {'name': 'Galactose', 'unit_name': 'G'},
 1078: {'name': 'Xylitol', 'unit_name': 'G'},
 1079: {'name': 'Fiber, total dietary', 'unit_name': 'G'},
 1081: {'name': 'Ribose', 'unit_name': 'G'},
 1082: {'name': 'Fiber, soluble', 'unit_name': 'G'},
 1084: {'name': 'Fiber, insoluble', 'unit_name': 'G'},
 1085: {'name': 'Total fat (NLEA)', 'unit_name': 'G'},
 1086: {'name': 'Total sugar alcohols', 'unit_name': 'G'},
 1087: {'name': 'Calcium, Ca', 'unit_name': 'MG'},
 1088: {'name': 'Chlorine, Cl', 'unit_name': 'MG'},
 1089: {'name': 'Iron, Fe', 'unit_name': 'MG'},
 1090: {'name': 'Magnesium, Mg', 'unit_name': 'MG'},
 1091: {'name': 'Phosphorus, P', 'unit_name': 'MG'},
 1092: {'name': 'Potassium, K', 'unit_name': 'MG'},
 1093: {'name': 'Sodium, Na', 'unit_name': 'MG'},
 1094: {'name': 'Sulfur, S', 'unit_name': 'MG'},
 1095: {'name': 'Zinc, Zn', 'unit_name': 'MG'},
 1096: {'name': 'Chromium, Cr', 'unit_name': 'UG'},
 1097: {'name': 'Cobalt, Co', 'unit_name': 'UG'},
 1098: {'name': 'Copper, Cu', 'unit_name': 'MG'},
 1099: {'name': 'Fluoride, F', 'unit_name': 'UG'},
 1100: {'name': 'Iodine, I', 'unit_name': 'UG'},
 1101: {'name': 'Manganese, Mn', 'unit_name': 'MG'},
 1102: {'name': 'Molybdenum, Mo', 'unit_name': 'UG'},
 1103: {'name': 'Selenium, Se', 'unit_name': 'UG'},
 1104: {'name': 'Vitamin A, IU', 'unit_name': 'IU'},
 1105: {'name': 'Retinol', 'unit_name': 'UG'},
 1106: {'name': 'Vitamin A, RAE', 'unit_name': 'UG'},
 1107: {'name': 'Carotene, beta', 'unit_name': 'UG'},
 1108: {'name': 'Carotene, alpha', 'unit_name': 'UG'},
 1109: {'name': 'Vitamin E (alpha-tocopherol)', 'unit_name': 'MG'},
 1110: {'name': 'Vitamin D (D2 + D3), International Units', 'unit_name': 'IU'},
 1111: {'name': 'Vitamin D2 (ergocalciferol)', 'unit_name': 'UG'},
 1112: {'name': 'Vitamin D3 (cholecalciferol)', 'unit_name': 'UG'},
 1113: {'name': '25-hydroxycholecalciferol', 'unit_name': 'UG'},
 1114: {'name': 'Vitamin D (D2 + D3)', 'unit_name': 'UG'},
 1116: {'name': 'Phytoene', 'unit_name': 'UG'},
 1117: {'name': 'Phytofluene', 'unit_name': 'UG'},
 1119: {'name': 'Zeaxanthin', 'unit_name': 'UG'},
 1120: {'name': 'Cryptoxanthin, beta', 'unit_name': 'UG'},
 1121: {'name': 'Lutein', 'unit_name': 'UG'},
 1122: {'name': 'Lycopene', 'unit_name': 'UG'},
 1123: {'name': 'Lutein + zeaxanthin', 'unit_name': 'UG'},
 1124: {'name': 'Vitamin E (label entry primarily)', 'unit_name': 'IU'},
 1125: {'name': 'Tocopherol, beta', 'unit_name': 'MG'},
 1126: {'name': 'Tocopherol, gamma', 'unit_name': 'MG'},
 1127: {'name': 'Tocopherol, delta', 'unit_name': 'MG'},
 1128: {'name': 'Tocotrienol, alpha', 'unit_name': 'MG'},
 1129: {'name': 'Tocotrienol, beta', 'unit_name': 'MG'},
 1130: {'name': 'Tocotrienol, gamma', 'unit_name': 'MG'},
 1131: {'name': 'Tocotrienol, delta', 'unit_name': 'MG'},
 1137: {'name': 'Boron, B', 'unit_name': 'UG'},
 1146: {'name': 'Nickel, Ni', 'unit_name': 'UG'},
 1158: {'name': 'Vitamin E', 'unit_name': 'MG_ATE'},
 1159: {'name': 'cis-beta-Carotene', 'unit_name': 'UG'},
 1160: {'name': 'cis-Lycopene', 'unit_name': 'UG'},
 1161: {'name': 'cis-Lutein/Zeaxanthin', 'unit_name': 'UG'},
 1162: {'name': 'Vitamin C, total ascorbic acid', 'unit_name': 'MG'},
 1165: {'name': 'Thiamin', 'unit_name': 'MG'},
 1166: {'name': 'Riboflavin', 'unit_name': 'MG'},
 1167: {'name': 'Niacin', 'unit_name': 'MG'},
 1170: {'name': 'Pantothenic acid', 'unit_name': 'MG'},
 1175: {'name': 'Vitamin B-6', 'unit_name': 'MG'},
 1176: {'name': 'Biotin', 'unit_name': 'UG'},
 1177: {'name': 'Folate, total', 'unit_name': 'UG'},
 1178: {'name': 'Vitamin B-12', 'unit_name': 'UG'},
 1180: {'name': 'Choline, total', 'unit_name': 'MG'},
 1181: {'name': 'Inositol', 'unit_name': 'MG'},
 1183: {'name': 'Vitamin K (Menaquinone-4)', 'unit_name': 'UG'},
 1184: {'name': 'Vitamin K (Dihydrophylloquinone)', 'unit_name': 'UG'},
 1185: {'name': 'Vitamin K (phylloquinone)', 'unit_name': 'UG'},
 1186: {'name': 'Folic acid', 'unit_name': 'UG'},
 1187: {'name': 'Folate, food', 'unit_name': 'UG'},
 1188: {'name': '5-methyl tetrahydrofolate (5-MTHF)', 'unit_name': 'UG'},
 1190: {'name': 'Folate, DFE', 'unit_name': 'UG'},
 1191: {'name': '10-Formyl folic acid (10HCOFA)', 'unit_name': 'UG'},
 1192: {'name': '5-Formyltetrahydrofolic acid (5-HCOH4', 'unit_name': 'UG'},
 1194: {'name': 'Choline, free', 'unit_name': 'MG'},
 1195: {'name': 'Choline, from phosphocholine', 'unit_name': 'MG'},
 1196: {'name': 'Choline, from phosphotidyl choline', 'unit_name': 'MG'},
 1197: {'name': 'Choline, from glycerophosphocholine', 'unit_name': 'MG'},
 1198: {'name': 'Betaine', 'unit_name': 'MG'},
 1199: {'name': 'Choline, from sphingomyelin', 'unit_name': 'MG'},
 1210: {'name': 'Tryptophan', 'unit_name': 'G'},
 1211: {'name': 'Threonine', 'unit_name': 'G'},
 1212: {'name': 'Isoleucine', 'unit_name': 'G'},
 1213: {'name': 'Leucine', 'unit_name': 'G'},
 1214: {'name': 'Lysine', 'unit_name': 'G'},
 1215: {'name': 'Methionine', 'unit_name': 'G'},
 1216: {'name': 'Cystine', 'unit_name': 'G'},
 1217: {'name': 'Phenylalanine', 'unit_name': 'G'},
 1218: {'name': 'Tyrosine', 'unit_name': 'G'},
 1219: {'name': 'Valine', 'unit_name': 'G'},
 1220: {'name': 'Arginine', 'unit_name': 'G'},
 1221: {'name': 'Histidine', 'unit_name': 'G'},
 1222: {'name': 'Alanine', 'unit_name': 'G'},
 1223: {'name': 'Aspartic acid', 'unit_name': 'G'},
 1224: {'name': 'Glutamic acid', 'unit_name': 'G'},
 1225: {'name': 'Glycine', 'unit_name': 'G'},
 1226: {'name': 'Proline', 'unit_name': 'G'},
 1227: {'name': 'Serine', 'unit_name': 'G'},
 1228: {'name': 'Hydroxyproline', 'unit_name': 'G'},
 1232: {'name': 'Cysteine', 'unit_name': 'G'},
 1233: {'name': 'Glutamine', 'unit_name': 'G'},
 1234: {'name': 'Taurine', 'unit_name': 'G'},
 1235: {'name': 'Sugars, added', 'unit_name': 'G'},
 1242: {'name': 'Vitamin E, added', 'unit_name': 'MG'},
 1246: {'name': 'Vitamin B-12, added', 'unit_name': 'UG'},
 1253: {'name': 'Cholesterol', 'unit_name': 'MG'},
 1257: {'name': 'Fatty acids, total trans', 'unit_name': 'G'},
 1258: {'name': 'Fatty acids, total saturated', 'unit_name': 'G'},
 1259: {'name': '4:0', 'unit_name': 'G'},
 1260: {'name': '6:0', 'unit_name': 'G'},
 1261: {'name': '8:0', 'unit_name': 'G'},
 1262: {'name': '10:0', 'unit_name': 'G'},
 1263: {'name': '12:0', 'unit_name': 'G'},
 1264: {'name': '14:0', 'unit_name': 'G'},
 1265: {'name': '16:0', 'unit_name': 'G'},
 1266: {'name': '18:0', 'unit_name': 'G'},
 1267: {'name': '20:0', 'unit_name': 'G'},
 1268: {'name': '18:1', 'unit_name': 'G'},
 1269: {'name': '18:2', 'unit_name': 'G'},
 1270: {'name': '18:3', 'unit_name': 'G'},
 1271: {'name': '20:4', 'unit_name': 'G'},
 1272: {'name': '22:6 n-3 (DHA)', 'unit_name': 'G'},
 1273: {'name': '22:0', 'unit_name': 'G'},
 1274: {'name': '14:1', 'unit_name': 'G'},
 1275: {'name': '16:1', 'unit_name': 'G'},
 1276: {'name': '18:4', 'unit_name': 'G'},
 1277: {'name': '20:1', 'unit_name': 'G'},
 1278: {'name': '20:5 n-3 (EPA)', 'unit_name': 'G'},
 1279: {'name': '22:1', 'unit_name': 'G'},
 1280: {'name': '22:5 n-3 (DPA)', 'unit_name': 'G'},
 1281: {'name': '14:1 t', 'unit_name': 'G'},
 1283: {'name': 'Phytosterols', 'unit_name': 'MG'},
 1285: {'name': 'Stigmasterol', 'unit_name': 'MG'},
 1286: {'name': 'Campesterol', 'unit_name': 'MG'},
 1287: {'name': 'Brassicasterol', 'unit_name': 'MG'},
 1288: {'name': 'Beta-sitosterol', 'unit_name': 'MG'},
 1289: {'name': 'Campestanol', 'unit_name': 'MG'},
 1292: {'name': 'Fatty acids, total monounsaturated', 'unit_name': 'G'},
 1293: {'name': 'Fatty acids, total polyunsaturated', 'unit_name': 'G'},
 1294: {'name': 'Beta-sitostanol', 'unit_name': 'MG'},
 1296: {'name': 'Delta-5-avenasterol', 'unit_name': 'MG'},
 1298: {'name': 'Phytosterols, other', 'unit_name': 'MG'},
 1299: {'name': '15:0', 'unit_name': 'G'},
 1300: {'name': '17:0', 'unit_name': 'G'},
 1301: {'name': '24:0', 'unit_name': 'G'},
 1303: {'name': '16:1 t', 'unit_name': 'G'},
 1304: {'name': '18:1 t', 'unit_name': 'G'},
 1305: {'name': '22:1 t', 'unit_name': 'G'},
 1306: {'name': '18:2 t not further defined', 'unit_name': 'G'},
 1307: {'name': '18:2 i', 'unit_name': 'G'},
 1310: {'name': '18:2 t,t', 'unit_name': 'G'},
 1311: {'name': '18:2 CLAs', 'unit_name': 'G'},
 1312: {'name': '24:1 c', 'unit_name': 'G'},
 1313: {'name': '20:2 n-6 c,c', 'unit_name': 'G'},
 1314: {'name': '16:1 c', 'unit_name': 'G'},
 1315: {'name': '18:1 c', 'unit_name': 'G'},
 1316: {'name': '18:2 n-6 c,c', 'unit_name': 'G'},
 1317: {'name': '22:1 c', 'unit_name': 'G'},
 1321: {'name': '18:3 n-6 c,c,c', 'unit_name': 'G'},
 1323: {'name': '17:1', 'unit_name': 'G'},
 1325: {'name': '20:3', 'unit_name': 'G'},
 1329: {'name': 'Fatty acids, total trans-monoenoic', 'unit_name': 'G'},
 1330: {'name': 'Fatty acids, total trans-dienoic', 'unit_name': 'G'},
 1331: {'name': 'Fatty acids, total trans-polyenoic', 'unit_name': 'G'},
 1332: {'name': '13:0', 'unit_name': 'G'},
 1333: {'name': '15:1', 'unit_name': 'G'},
 1334: {'name': '22:2', 'unit_name': 'G'},
 1335: {'name': '11:0', 'unit_name': 'G'},
 1368: {'name': 'Epigallocatechin-3-gallate', 'unit_name': 'MG'},
 1403: {'name': 'Inulin', 'unit_name': 'G'},
 1404: {'name': '18:3 n-3 c,c,c (ALA)', 'unit_name': 'G'},
 1405: {'name': '20:3 n-3', 'unit_name': 'G'},
 1406: {'name': '20:3 n-6', 'unit_name': 'G'},
 1408: {'name': '20:4 n-6', 'unit_name': 'G'},
 1409: {'name': '18:3i', 'unit_name': 'G'},
 1410: {'name': '21:5', 'unit_name': 'G'},
 1411: {'name': '22:4', 'unit_name': 'G'},
 1412: {'name': '18:1-11 t (18:1t n-7)', 'unit_name': 'G'},
 1414: {'name': '20:3 n-9', 'unit_name': 'G'},
 2000: {'name': 'Sugars, total including NLEA', 'unit_name': 'G'},
 2003: {'name': '5:0', 'unit_name': 'G'},
 2004: {'name': '7:0', 'unit_name': 'G'},
 2005: {'name': '9:0', 'unit_name': 'G'},
 2006: {'name': '21:0', 'unit_name': 'G'},
 2007: {'name': '23:0', 'unit_name': 'G'},
 2008: {'name': '12:1', 'unit_name': 'G'},
 2009: {'name': '14:1 c', 'unit_name': 'G'},
 2010: {'name': '17:1 c', 'unit_name': 'G'},
 2012: {'name': '20:1 c', 'unit_name': 'G'},
 2013: {'name': '20:1 t', 'unit_name': 'G'},
 2014: {'name': '22:1 n-9', 'unit_name': 'G'},
 2015: {'name': '22:1 n-11', 'unit_name': 'G'},
 2016: {'name': '18:2 c', 'unit_name': 'G'},
 2018: {'name': '18:3 c', 'unit_name': 'G'},
 2019: {'name': '18:3 t', 'unit_name': 'G'},
 2020: {'name': '20:3 c', 'unit_name': 'G'},
 2021: {'name': '22:3', 'unit_name': 'G'},
 2022: {'name': '20:4 c', 'unit_name': 'G'},
 2023: {'name': '20:5 c', 'unit_name': 'G'},
 2024: {'name': '22:5 c', 'unit_name': 'G'},
 2025: {'name': '22:6 c', 'unit_name': 'G'},
 2026: {'name': '20:2 c', 'unit_name': 'G'},
 2028: {'name': 'trans-beta-Carotene', 'unit_name': 'UG'},
 2029: {'name': 'trans-Lycopene', 'unit_name': 'UG'},
 2032: {'name': 'Cryptoxanthin, alpha', 'unit_name': 'UG'},
 2033: {'name': 'Total dietary fiber (AOAC 2011.25)', 'unit_name': 'G'}}

In [15]:
final.rename(inplace=True, axis=1, mapper= lambda x: nutri_dict[x]["name"] if isinstance(x, int) else x)

In [16]:
final

,Nitrogen,Protein,Total lipid (fat),"Carbohydrate, by difference",Ash,Energy,Starch,Sucrose,Glucose (dextrose),Fructose,...,20:5 c,22:5 c,22:6 c,20:2 c,trans-beta-Carotene,trans-Lycopene,"Cryptoxanthin, alpha",Total dietary fiber (AOAC 2011.25),data_type,description
fdc_id,,,,,,,,,,,,,,,,,,,,,
167512,NaN,5.88,13.24,41.18,3.50,307.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,sr_legacy_food,"Pillsbury Golden Layer Buttermilk Biscuits, Ar..."
167513,NaN,4.34,11.27,53.42,3.08,330.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,sr_legacy_food,"Pillsbury, Cinnamon Rolls with Icing, refriger..."
167514,NaN,6.10,3.70,79.80,7.20,377.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,sr_legacy_food,"Kraft Foods, Shake N Bake Original Recipe, Coa..."
167515,NaN,8.00,1.80,46.00,1.60,232.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,sr_legacy_food,"George Weston Bakeries, Thomas English Muffins"
167516,NaN,6.58,9.22,41.05,2.81,273.0,35.51,2.67,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,sr_legacy_food,"Waffles, buttermilk, frozen, ready-to-heat"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
810268,NaN,0.83,0.00,2.50,NaN,12.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,branded_food,Santiam French Style Green Beans 14.5oz
810270,NaN,0.83,0.00,2.50,NaN,12.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,branded_food,Santiam Cut Wax Beans 14.5oz
810272,NaN,2.08,0.42,5.42,NaN,33.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,branded_food,CAMPBELL'S CHUNKY SOUP CHICKEN & VEGETABLE
810274,NaN,2.40,0.00,8.80,NaN,48.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,branded_food,Santiam Sweet Peas 15oz
810276,NaN,1.67,1.25,10.00,NaN,58.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,branded_food,PREGO SAUCES TOMATO & MUSHROOM